[package]
edition = "2021"
name = "poetry-cli"
version = "0.1.0"

[dependencies]
anyhow = {version = "1.0", features = ["backtrace"]}
dialoguer = "*"
clap = {version = "*", features = ["cargo", "derive"] }

[dependencies.poetry]
path = "poetry"

[workspace]
