[package]
edition = "2021"
name = "poetry-cli"
version = "0.1.0"
[dependencies]
dialoguer = "*"
tokio = "*"

[dependencies.anyhow]
features = ["backtrace"]
version = "1.0"

[dependencies.clap]
features = ["cargo", "derive"]
version = "*"

[dependencies.poetry]
path = "poetry"

[workspace]
