[package]
edition = "2021"
name = "poetry"
version = "0.1.0"

[dependencies]
thiserror = {version = "1.0"}
chrono = "*"
serde = {version = "1.0", features = ["derive"]}
toml = {version = "*", features = ["preserve_order"]}
